# Generated by Django 5.0.6 on 2024-06-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='public',
            new_name='is_private',
        ),
    ]
