# Generated by Django 5.0.6 on 2024-06-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_public_task_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
